service: aws-lambda-api-service

frameworkVersion: '2.55.0'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  profile: deploy-aws
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /helloworld
